/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background:                 '#f8f9fa',
        surface:                    '#f8f9fa',
        'surface-dim':              '#d9dadb',
        'surface-bright':           '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f3f4f5',
        'surface-container':        '#edeeef',
        'surface-container-high':   '#e7e8e9',
        'surface-container-highest':'#e1e3e4',
        'surface-variant':          '#e1e3e4',
        'on-surface':               '#191c1d',
        'on-surface-variant':       '#404943',
        'inverse-surface':          '#2e3132',
        'inverse-on-surface':       '#f0f1f2',
        outline:                    '#707973',
        'outline-variant':          '#bfc9c1',
        'surface-tint':             '#2c694e',

        primary:                    '#0f5238',
        'on-primary':               '#ffffff',
        'primary-container':        '#2d6a4f',
        'on-primary-container':     '#a8e7c5',
        'inverse-primary':          '#95d4b3',
        'primary-fixed':            '#b1f0ce',
        'primary-fixed-dim':        '#95d4b3',
        'on-primary-fixed':         '#002114',
        'on-primary-fixed-variant': '#0e5138',

        secondary:                  '#0060ac',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#68abff',
        'on-secondary-container':   '#003e73',
        'secondary-fixed':          '#d4e3ff',
        'secondary-fixed-dim':      '#a4c9ff',
        'on-secondary-fixed':       '#001c39',
        'on-secondary-fixed-variant':'#004883',

        tertiary:                   '#832800',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#a53d12',
        'on-tertiary-container':    '#ffcfbf',
        'tertiary-fixed':           '#ffdbcf',
        'tertiary-fixed-dim':       '#ffb59c',
        'on-tertiary-fixed':        '#380c00',
        'on-tertiary-fixed-variant':'#822800',

        error:                      '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',

        'on-background':            '#191c1d',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'h1':       ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'h2':       ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'h3':       ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg':  ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':  ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      borderRadius: {
        sm:      '0.25rem',
        DEFAULT: '0.5rem',
        md:      '0.75rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      spacing: {
        xs:     '0.25rem',
        sm:     '0.5rem',
        md:     '1rem',
        lg:     '1.5rem',
        xl:     '2rem',
        xxl:    '4rem',
        gutter: '1.5rem',
        margin: '2rem',
      },
      boxShadow: {
        card:   '0 4px 24px -4px rgba(0, 96, 172, 0.06)',
        modal:  '0 24px 48px -12px rgba(0,0,0,0.12)',
        nav:    '0 -4px 20px 0 rgba(0,0,0,0.05)',
      },
    },
  },
  plugins: [],
}
